### ISSUE TITLE
[Enhancement] Add Prebuilt bundled Watermark resources

### ISSUE THREAD

**Issue by dansiegel** [dansiegel/Mobile.BuildTools#103]
### SUMMARY

It can get a little tedious to have to manage a bunch of assets... the Mobile.BuildTools should ship with a variety of pre-built watermark assets.

### DETAILS

Since the Mobile.BuildTools will now handle image watermarking which is largely targeted at app icons we should include several built in watermark templates. We could use someone who has some graphics expertise who can come up with a few different styles and perhaps color options as well.

| Input Image | Watermark Image | Output Image |
|:-:|:-:|:-:|
| ![dotnetbot](https://user-images.githubusercontent.com/3860573/76171066-b88adc80-6144-11ea-827f-45a9068015a1.png) | ![beta-version](https://user-images.githubusercontent.com/3860573/76171052-aad55700-6144-11ea-88c8-5770a2ee04be.png) | ![dotnetbot-beta](https://user-images.githubusercontent.com/3860573/76171080-d48e7e00-6144-11ea-9db9-54b3f61d5fdf.png) |

We will want to provide at least 4 out of the box variants for each of the following:

- Dev
- Debug
- QA
- UAT
- Stage
- Preview
- Alpha
- Beta

**NOTE** All resources should be added to `src/Mobile.BuildTools/Resources/`

**Comment by seanalford** [comment]
@dansiegel I'll put something together for you to take a look at.  I'll submit a PR tonight or early AM.

**Comment by dansiegel** [comment]
closing this as this appears to have been resolved by #112... I know there are will be some follow up work on this. Thanks for the help @seanalford
