### ISSUE TITLE
Copying artifacts error MSB3024, "could not copy the file to destination the file" when building to device

### ISSUE THREAD

**Issue by jackv24** [dansiegel/Mobile.BuildTools#119]
# Description

I was having a similar problem to [this issue](https://github.com/dansiegel/Mobile.BuildTools/issues/39), but after following these steps I'm now getting a different problem related to copying build artifacts.

The error message is:

`/Users/jackv/.nuget/packages/mobile.buildtools/1.4.0.638/build/Mobile.BuildTools.targets(5,5): Error MSB3024: Could not copy the file "bin/iPhone/Debug/device-builds/ipad7.3-13.4/ComicWrap.iOS.app/LaunchScreen.storyboardc/UIViewController-X5k-f2-b5h.nib" to the destination file "/Users/jackv/Documents/Development/ComicWrap/Artifacts/ComicWrap.iOS.app.dSYM/ComicWrap.iOS.app/LaunchScreen.storyboardc/UIViewController-X5k-f2-b5h.nib", because the destination is a folder instead of a file. To copy the source file into a folder, consider using the DestinationFolder parameter instead of DestinationFiles. (MSB3024) (ComicWrap.iOS)`

## Reproduction Steps

1. Clone project
2. Open in Visual Studio for Mac
3. Set build config to Debug>[Device] (this error does not happen when building for a simulator)
4. Build

## Expected Behavior

Application builds without errors.

## Actual Behavior

Build fails with the above error.

## Environment

- OS: macOS Catalina 10.15.4 
- IDE: Visual Studio for Mac Community
- BuildTools Version: 1.4.0.638 (latest stable)
- IDE Version: 8.5 (build 3183)
- Build Target Framework: Xamarin.iOS (Xamarin Forms)

## Reproduction App

I did not get this error in a new solution, so it must be how my project is setup [here's the project I'm having the issue in](https://github.com/jackv24/ComicWrap)

**Comment by dansiegel** [comment]
@jackv24 this is a known issue with 1.4... I don't have any plans on back porting a fix... you can try the new 2.0 preview as i haven't seen the issue there. Otherwise you can create a `Directory.Build.props` in the root directory as follows and it will disable the broken copy task.

```xml
<Project>
  <PropertyGroup>
    <DisableBuildToolsArtifactCopy>true</DisableBuildToolsArtifactCopy>
  </PropertyGroup>
</Project>
```

**Comment by jackv24** [comment]
Disabling the broken copy task works fine, thanks!
