### ISSUE TITLE
GenerateGitReleaseNotesTask

### ISSUE THREAD

**Issue by rickymarks** [dansiegel/Mobile.BuildTools#121]
# Description
I was having the same problem as [this issue](https://github.com/dansiegel/Mobile.BuildTools/issues/119) and took the route of upgrading the package to version 2.0. The problem persisted but I disabled the ArtifactsCopy on the buildtools.json file and the error seems to be fixed. The app compiles on Release and Debug Configurations on my local machine. However, both iOS and Android failed to build on AppCenter. 
According to the logs the error was on the GenerateGitReleaseNotesTask. 
I proceeded to disable the releaseNotes on the buildtools.json. 
The problem seems to be fixed on the iOS build in App Center but on the Android part I still get the error: 

> /Users/runner/runners/2.166.2/work/1/s/Xamarin_FMMobileApp/Xamarin_FMMobileApp.Android/Xamarin_FMMobileApp.Android.csproj" (PackageForAndroid target) (1) ->
(GenerateGitReleaseNotes target) -> 
  /Users/runner/.nuget/packages/mobile.buildtools/2.0.0.1007-pre/build/GitVersioning.targets(10,5): error : Unhandled error while executing GenerateGitReleaseNotesTask [/Users/runner/runners/2.166.2/work/1/s/Xamarin_FMMobileApp/Xamarin_FMMobileApp.Android/Xamarin_FMMobileApp.Android.csproj]
  /Users/runner/.nuget/packages/mobile.buildtools/2.0.0.1007-pre/build/GitVersioning.targets(10,5): error : Could not find a part of the path "/Users/runner/runners/2.166.2/work/1/s/Xamarin_FMMobileApp/.vs/generated-releasenotes.a56447e1f13900b11fbe54a17d3716eb62b49bc3". [/Users/runner/runners/2.166.2/work/1/s/Xamarin_FMMobileApp/Xamarin_FMMobileApp.Android/Xamarin_FMMobileApp.Android.csproj]

## Expected Behavior

Build without generating release notes.

## Actual Behavior

Exception on the GenerateGitReleaseNotes 

## Environment

- OS: Windows 10
- IDE: VS2019
- BuildTools Version: 2.0.0.1007-pre
- IDE Version: Version 16.5.3
- Build Target Framework: Xamarin.Android

## Reproduction App
Can't include the logs because it's company app. Although I could send them to you privately.

**Comment by dansiegel** [comment]
thanks for the bug report. should be an easy fix for the issue... that said to disable the release notes task you should just need to edit the buildtools.json and disable the task there.

```json
{
  "$schema": "https://mobilebuildtools.com/schemas/v2/buildtools.schema.json",
  "releaseNotes": {
    "disable": true
  }
}
```

**Comment by rickymarks** [comment]
I tried disabling the releaseNotes task on the buildtools.json file and the error seems to be fixed on iOS but on the Android App the issue still persists. 

Here is my buildstools.json that I'm currently using:

`{
  "$schema": "https://mobilebuildtools.com/schemas/v2/buildtools.schema.json",
  "appConfig": {
    "strategy": "TransformOnly",
    "disable": true
  },
  "artifactCopy": {
    "disable": true
  },
  "automaticVersioning": {
    "behavior": "PreferBuildNumber",
    "environment": "All",
    "versionOffset": 0,
    "disable": true
  },
  "css": {
    "minify": false,
    "bundleScss": false,
    "disable": true
  },
  "images": {
    "directories": null,
    "conditionalDirectories": null,
    "watermarkOpacity": null,
    "disable": true
  },
  "manifests": {
    "token": "$",
    "variablePrefix": "Manifest_",
    "missingTokensAsErrors": false,
    "disable": true
  },
  "releaseNotes": {
    "disable": true
  },
  "projectSecrets": {
    "Xamarin_FMMobileApp": {
      "disable": false,
      "delimiter": ";",
      "prefix": "BuildTools_",
      "className": "Secrets",
      "namespace": "Helpers",
      "properties": [
        {
          "name": "AppCenter",
          "type": "String",
          "isArray": false
        },
        {
          "name": "PushNotificationHub",
          "type": "String",
          "isArray": false
        },
        {
          "name": "PushHubName",
          "type": "String",
          "isArray": false
        },
        {
          "name": "FMProxy",
          "type": "String",
          "isArray": false
        },
        {
          "name": "FMProxyKey",
          "type": "String",
          "isArray": false
        }
      ]
    }
  },
  "debug": false
}`

**Comment by dansiegel** [comment]
that's very strange... can you provide a sample that reproduces this issue?

**Comment by rickymarks** [comment]
I created this [sample app](https://github.com/rickymarks/MobileBuildToolsSampleReleaseNotes.git) that generated the same issue.

What I did to create this sample is: 

1. Create a Xamarin Forms App (Android only)
2. Added Mobile Build Tools v2.0
3. Added the secrets.json file
4. Connected the repository to app center
5. Created a build configuration on release with the secrets as environment variables.

![image](https://user-images.githubusercontent.com/38436835/79394269-0dd8bb80-7f45-11ea-88da-d0fcc4fe08a3.png)

**Comment by dansiegel** [comment]
Great... thanks @rickymarks I'll take a look at your sample as soon as I get a moment.

**Comment by rickymarks** [comment]
@dansiegel Any update on this??

**Comment by dansiegel** [comment]
@rickymarks I'll get to this when I have time. Please keep in mind this is an open source library. You are welcome to dig into the issue yourself and submit a PR or you can contact me via email if you are interested in paid support.

**Comment by rickymarks** [comment]
No problem. I wasn't rushing you by any means and I just wanted to know if you had the time to look into it. 

I've been trying to look into the problem to no avail due to the fact that I have never worked on this kind of project before. 

If you could point me to any kind of documentation on how the project works I'll gladly study it and see if that could help me narrow down the problem.

**Comment by dansiegel** [comment]
as per issue #127 it would seem this issue is likely due to the lack of a .vs folder. It should probably be an easy fix. I'm a bit busy at the moment working on some Prism updates. If someone would like to do a PR it would seem we just need to ensure that the directory exists before writing the file the BuildTools stores there.

**Comment by owenonline** [comment]
I am still getting this error using the latest version of everything and disabling release notes:
```{
  "$schema": "https://mobilebuildtools.com/schemas/v2/buildtools.schema.json",
  "releaseNotes": {
    "disable": true
  }
}
```
