### ISSUE TITLE
Local project build failure due to config manager bundle task issue with app.{AppConfigEnvironment}.config

### ISSUE THREAD

**Issue by T3zler** [dansiegel/Mobile.BuildTools#131]
# Description

When building a Xamarin Forms project the build is failing due to the configuration bundle build.

The only resolution to this is to create 'app.{AppConfigEnvironment}.config' for each env config i.e. Debug and Release.

The exception reported is:

```
Mobile.BuildTools.2.0.0.1007-pre\build\ConfigurationManager.targets(31,5): error : Unhandled error while executing ConfigurationManagerHandlerTask
Mobile.BuildTools.2.0.0.1007-pre\build\ConfigurationManager.targets(31,5): error : Object reference not set to an instance of an object.
Mobile.BuildTools.2.0.0.1007-pre\build\ConfigurationManager.targets(31,5): warning : **************** DEBUG OUTPUT ****************
Mobile.BuildTools.2.0.0.1007-pre\build\ConfigurationManager.targets(31,5): warning : System.NullReferenceException: Object reference not set to an instance of an object.
Mobile.BuildTools.2.0.0.1007-pre\build\ConfigurationManager.targets(31,5): warning :    at Mobile.BuildTools.Tasks.ConfigurationManagerHandlerTask.ExecuteInternal(IBuildConfiguration config) in d:\a\1\s\src\Mobile.BuildTools\Tasks\ConfigurationManagerHandlerTask.cs:line 62
Mobile.BuildTools.2.0.0.1007-pre\build\ConfigurationManager.targets(31,5): warning :    at Mobile.BuildTools.Tasks.BuildToolsTaskBase.Execute() in d:\a\1\s\src\Mobile.BuildTools\Tasks\BuildToolsTaskBase.cs:line 67
```

I think this is related to the .ItemSpec of transformFile when transformFile  is Null.

```
var transformFile = GetTaskItem(InputConfigFiles, $"app.{AppConfigEnvironment}.config");
var outputs = GeneratedAppConfig.Select(x => Models.Configuration.ExpectedAppConfig.FromTaskItem(x));
var generator = new ConfigurationManagerTransformationGenerator(config)
{
	BaseConfigPath = rootConfigFile.ItemSpec,
	TransformFilePath = transformFile.ItemSpec,
	ExpectedConfigs = outputs
};
```

This assumes there is ALWAYS a file for all env builds.
I've played with the various strategies and none of them alter behaviour.

The ConfigurationManagerTransformationGenerator is missing the disable functionality like some of the other generators, so the only way currently around this is to ensure app files exist for each build you run, even if you have no need for them!

Not fully knowing full design intention in regards to this, I'm hesitant to submit any pull request myself, other than to possibly add the disable into this generator but unsure if that's desired.

**Comment by dansiegel** [comment]
Thanks for the report. I'll take a look into this once I get a moment

**Comment by dansiegel** [comment]
@T3zler I can't really confirm whether or not this is fixed as you never provided a sample app. I believe this was fixed in the CI feed.
