### ISSUE TITLE
Can't use IConfiguration after installing Mobile.BuildTools and Mobile.BuildTools.Configuration 

### ISSUE THREAD

**Issue by DamienDoumer** [dansiegel/Mobile.BuildTools#150]
# Description

This is kind of weird, may be I might be missing something, I installed Mobile.BuildTools and Mobile.BuildTools.Configuration nugget packages latest versions, but I couldn't access "IConfigurationManager" nor ConfigurationManager
I tried adding a "using Mobile.BuildTools.Configuration" but still didn;t work, and Visualstudio didn't find the namespace

So I donwloaded the source code and found they were present in the namespace "Mobile.BuildTools.Configuration" and used by the sample present in the solution. 
This issue might be stupid, but I don't understand is this behaviour normal ? 

## Reproduction Steps

1. Install Mobile.BuildTools and Mobile.BuildTools.Configuration  nugget packages
2. Try to access the ConfigurationManager 
3. It is not found 

## Expected Behavior

Install Mobile.BuildTools and Mobile.BuildTools.Configuration 
Add "using Mobile.BuildTools.Configuration"
Call "ConfigurationManager.Current", 
It is found and works in your code.

**Comment by dansiegel** [comment]
@DamienDoumer can you please provide a reproduction

**Comment by DamienDoumer** [comment]
Like a project with the package ? Ok, will do that.

**Comment by dansiegel** [comment]
yea... just like File -> New Project with a reference to the same package that you're referencing in your project that demonstrates the issue you've brought up here.

**Comment by DamienDoumer** [comment]
Hello, here it is.
The secrets class is created successfully. But I can't use the config in code, though the packages are installed in the shared .net standard project.
[Repro.zip](https://github.com/dansiegel/Mobile.BuildTools/files/5338894/Repro.zip)

**Comment by dansiegel** [comment]
Thanks for the repro... I'll take a look at this as I get time

**Comment by dansiegel** [comment]
@DamienDoumer looking at your sample here there are a couple of issues

1. The app.config is meant to be in the head project (iOS/Android) NOT a shared project.
1. The package has been added with some bad properties which I'll have to address but it's a simple fix... right now you have:

```xml
<PackageReference Include="Mobile.BuildTools.Configuration" Version="2.0.0.1007-pre">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

Change that to:

```xml
<PackageReference Include="Mobile.BuildTools.Configuration" Version="2.0.0.1007-pre" />
```

The ConfigurationManager should be initialized on the platform

https://github.com/dansiegel/Mobile.BuildTools/blob/f57ab0b04b6f3b59f264eb1d1d094d40cb7c98b2/samples/AppConfigSample/src/AppConfigSample.Android/MainActivity.cs#L20

https://github.com/dansiegel/Mobile.BuildTools/blob/f57ab0b04b6f3b59f264eb1d1d094d40cb7c98b2/samples/AppConfigSample/src/AppConfigSample.iOS/AppDelegate.cs#L26

**Comment by DamienDoumer** [comment]
Hi @dansiegel  thankyou !

**Comment by dansiegel** [comment]
In looking at this a little further... it's actually already fixed in the Sponsor Connect feed.
