### ISSUE TITLE
Secrets class in VSMac not showing intellisense

### ISSUE THREAD

**Issue by soydachi** [dansiegel/Mobile.BuildTools#164]
# Description

The Secrets class created in obj is not showing in VSMac. Something is not working in mac. Same example works in a Windows machine.

## Reproduction Steps

1. Create .NET Standard class library
2. Create secret.json file
3. Add latest Mobile.BuildTools nuget package
4. Rebuild and see in some class if exist Secrets class.

## Expected Behavior

Work with the Secrets class created in obj folder

## Actual Behavior

Secrets class created in obj folder but vs for mac intellisense is not showing it up.

## Environment

- OS: [OSX]
- IDE: [VSMac]
- BuildTools Version: [1.4.0.638]
- IDE Version: [8.7.9]
- Build Target Framework: [netstandard2.0]

## Reproduction App

![image](https://user-images.githubusercontent.com/1771785/97592530-0bc9dc00-1a01-11eb-811c-3f5bde61f5ae.png)

**Comment by dansiegel** [comment]
Close the Solution and Reopen the solution, intellisense should pick up the class then. This is a known Code Generation issue that the .NET team is only now in C# 9 starting to understand...

**Comment by soydachi** [comment]
I already do that too and not working. This issue was know already yes. But this is something different I guess.

**Comment by dansiegel** [comment]
Don't know what to tell you. I use this in a lot of project and don't have this problem.. The way that the Mobile.BuildTools goes about Code Gen, it's actually been more reliable than the C# 9 code gen for getting picked up by intellisense.

**Comment by gaurakshay** [comment]
> Close the Solution and Reopen the solution, intellisense should pick up the class then. This is a known Code Generation issue that the .NET team is only now in C# 9 starting to understand...

This works for me (Visual Studio V 8.8.8, Build 12)

**Comment by marqueeeeeee** [comment]
I'am experiencing this also on the latest VS Mac 8.10.6, @soydachi did you resolve this issue?
