### ISSUE TITLE
Unable to compile BuildToolsSample

### ISSUE THREAD

**Issue by idrish-rishabhsoft** [dansiegel/Mobile.BuildTools#171]
# Description

I have just download code from master branch and I have opened **BuildToolsSample** and try to run in Mac Visual studio 2019. 

## Expected Behavior

It is simply run and compile or Need prerequisite steps that have to follow.    

## Actual Behavior

Not even complied.

## Environment

- Mac Visual studio version 8.8 (Build 2913)
- Xamarin.iOS : Version: 14.4.1.3
- Xamarin.mac : Version: 6.22.1.26
- .Net Core Runtime Versions:
	5.0.0
	3.1.8
	3.1.7
	3.1.4
	3.1.1
	2.2.0
	2.1.23
	2.1.22
	2.1.21
	2.1.18
	2.1.15
	2.0.0
- .Net Core SDK Versions:
	5.0.100
	3.1.402
	3.1.401
	3.1.300
	3.1.202
	3.1.101
	2.2.100
	2.0.0

**Comment by dansiegel** [comment]
The Sample Apps require that you have first build the Mobile.BuildTools locally.
