### ISSUE TITLE
secrets.json is ignored when new keys are added

### ISSUE THREAD

**Issue by havenindustries** [dansiegel/Mobile.BuildTools#180]
# Description

## Actual Behavior

What actually happened.

## Environment

- OS: [Windows 10|OSX]
- IDE: [VS2017|VSMac|CLI]
- BuildTools Version: [1.x.x]
- IDE Version: [1.x.x]
- Build Target Framework: [netstandard2.0|Xamarin.iOS|Xamarin.Android]

## Reproduction App

Please include a sample app that reproduces the issue and/or a binlog. Failure to reproduce either of these may lead to the issue being closed or ignored.

**Comment by havenindustries** [comment]
Update secrets.json with a new key, build, and it still has just the old keys in Secrets.cs.

**Comment by dansiegel** [comment]
you've provided no details

**Comment by havenindustries** [comment]
Sorry about that.  Basically no matter what I do in secrets.json the internal static class Secrets which is supposed to be generated from it never reflects the newly added keys to secrets.json.

**Comment by dansiegel** [comment]
@havenindustries there is a reason I have an issue template. You didn't follow it or provide me with any details which really prevents me from being able to help you.

**Comment by havenindustries** [comment]
Okay I mean it's pretty simple
1) update secrets.json
2) build
3) new keys added are not in the hidden class

this is with 2.0.0.1007-pre I'll downgrade and see if that corrects the issue.

**Comment by havenindustries** [comment]
Yep the latest stable release works so 1.4.0.638 is okay.  Thank you!

**Comment by dansiegel** [comment]
@havenindustries you would be correct that updating secrets.json with version 2.0 does not update the Secrets class. You must update the buildtools.json with the properties you want to add. 2.0 is a major rewrite that handles much more advanced scenarios and helps solve problems like not knowing if you're missing values for your secrets.json and build hosts like the Windows Agents for AzureDevOps that like to do a ToUpper() on all variable names.
