### ISSUE TITLE
Info.plist not updated

### ISSUE THREAD

**Issue by dansiegel** [dansiegel/Mobile.BuildTools#185]
# Description

When building the Info.plist is not updated for Build Versioning or any token replacements

## Expected Behavior

- Build
- Build Version is updated
- Tokens replaced from manifest.json or secrets.json

## Actual Behavior

- The Info.plist is not updated

## Reproduction App

E2E / Sample apps

**Comment by dansiegel** [comment]
moved to the 2.1 milestone

**Comment by biapar** [comment]
The same issue for me. Xamarin Forms 5.0
