### ISSUE TITLE
New logo for Mobile.BuildTools

### ISSUE THREAD

**Issue by reallinfo** [dansiegel/Mobile.BuildTools#24]
Hello, I designed a logo for MobileBuildTools. I used the mobile icon and ''build tools'' icon. I hope you like it. Also, If you there your a logo idea, i want to hear it.

![mbt](https://user-images.githubusercontent.com/36298335/39935166-d1a07d44-5550-11e8-82ea-2a9bb1e59af0.jpg)

**Comment by dansiegel** [comment]
That's wonderful. Can you DM me on [Twitter](https://twitter.com/DanJSiegel)

**Comment by reallinfo** [comment]
Sure, I sent a message.
