### ISSUE TITLE
The "LocateBuildToolsConfigTask" task was not found. Check the following: 

### ISSUE THREAD

**Issue by tinonetic** [dansiegel/Mobile.BuildTools#286]
Hi,

I upgraded to the latest version for a Xamarin.Android app,

I made no additional changes to the app. But just ran it.

It builds without error, but when I try to run it on the device, I get the following error:

> The "LocateBuildToolsConfigTask" task was not found. 
> Check the following: 
> 1.) The name of the task in the project file is the same as the name of the task class. 
> 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 
> 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin" directory.	
> 

Because I did not implement a task class with ITask interface, I looked for <UsingTask> as pointed out in **item 3**

But it is not there in the two versions of `Microsoft.Common.tasks` in the folder

## Expected Behavior

Mobile app must run on phone without issue as before with the old version of BuildTools

## Actual Behavior

It fails with error above

## Environment

- OS: Windows 10
- IDE: VS2019- BuildTools Version: 2.0.245
- IDE Version: 2019
- Build Target Framework: Xamarin.Android

**Comment by SuperCorks** [comment]
Any update on this, I have the same issue

**Comment by dansiegel** [comment]
I am closing this issue as there is no reproduction or anything that is really actionable here. From the sound of what you're describing please check out #282 as there is a hack that may fix your issue. If you have tried that hack and are still experiencing the issue please feel free to update this thread with the additional information and a simple sample project that reproduces the issue.
