### ISSUE TITLE
Use Default Namespace and not Assembly Name to generate Secrets class

### ISSUE THREAD

**Issue by roubachof** [dansiegel/Mobile.BuildTools#30]
![image](https://user-images.githubusercontent.com/596903/40831158-8b198cec-6588-11e8-9677-ee3c968efea0.png)

We carefully didn't put 'Android' in our namespace, to avoid namespace conflicts. But since the Secret class is generated with the assembly name, the project doesn't compile anymore:

![image](https://user-images.githubusercontent.com/596903/40831277-e04d3bdc-6588-11e8-8d33-e2c7befa95f8.png)

```csharp
namespace XXXX.XXXX.Android.Helpers
{
    internal static class Secrets
    {
        internal const bool IsQAMock = false;
    }
}
```

**Comment by dansiegel** [comment]
Can you please provide a repo. That shouldn't be a thing as the task has no idea what  the assembly name is, and is only passed the [RootNamespace](https://github.com/dansiegel/Mobile.BuildTools/blob/master/Mobile.BuildTools/build/Mobile.BuildTools.targets#L70). As a work around you can change your reference from `Android.OS` to `global::Android.OS` to fix your build for now.

**Comment by roubachof** [comment]
weird... cause the root namespace is indeed:

```xml
<RootNamespace>XXXX.XXXX.Droid</RootNamespace>
```

**Comment by dansiegel** [comment]
good catch...
