### ISSUE TITLE
No AppSettings class is generated during build

### ISSUE THREAD

**Issue by Sebosek** [dansiegel/Mobile.BuildTools#318]
# Description
I've added BuildTools to my existing Xamarin Forms app, added `appsettings.json`, and configured `buildtools` but no class with configuration is generated.

The folder structure is following:
```
+ .git
+ MyApp
   + MyApp
   + MyApp.Droid
   + MyApp.iOS
  MyApp.sln
  buildtools.json
  appsettings.json
```

`buildtools.json` file I've extended with the following:
```
  ...
  "appSettings": {
    "MyApp": [
      {
        "accessibility": "Internal",
        "className": "AppSettings",
        "namespace": "Helpers",
        "rootNamespace": null,
        "properties": [
          {
            "name": "Sample",
            "type": "String"
          },
          {
            "name": "AppCenterId",
            "type": "String"
          }
        ]
      }
    ]
  },
  "debug": true
}
```

And finally the `appsettings.json`
```
{
  "Sample": "Hello",
  "AppCenterId": "..."
}
```

Basically, I believe I did everything that should be done by documentation, but no class is generated during the build.
But to be honest, I'm not really sure, where should I put appsettings.json.
If it's an equivalent of appsettings.json from ASP.NET, then it should be placed into the root project, but the docs said "root folder" not the primary project from the solution.

## Reproduction Steps

1. Create a Xamarin Forms project
2. Do the same as it's written above
3. Build a project

## Expected Behavior

After the project builds a configuration class should be generated.

## Actual Behavior

No class is generated

## Environment

- OS: Windows 10
- IDE: Rider
- BuildTools Version: 2.0.245
- IDE Version: Build #RD-222.4167.23, built on September 9, 2022
- Build Target Framework: netstandard2.0

## Open questions
1. How to define a path for generated class?
2. In `buildtool.json` in the "appSettings" prop there is a key, in my case "MyApp". Does this key have any meaning?
3. Can I move `buildtools.json` and `appSettings.json` to the primary (netstandard2.0) project?

**Comment by dansiegel** [comment]
What you have here looks right but this is why you so often see requirements for a sample app that reproduces an issue. It's really impossible for me to tell you why you were having this issue...
