### ISSUE TITLE
Debuging on IOS on a device

### ISSUE THREAD

**Issue by tjxNathanMyers** [dansiegel/Mobile.BuildTools#33]
there are a couple issues with target file when trying to run a debug build on a physical device,

you get this error

[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form

**Comment by dansiegel** [comment]
I haven’t seen this issue come up. Can you provide a repo app that demonstrates the issue or dm me a binlog

**Comment by tjxNathanMyers** [comment]
i also ran into an issue,  that i'm trying to recreate which this line needs to be changed,  both these issues only happened on the developers Mac's not on Mobile Center.

  <Copy SourceFiles="$(__Generated_APK)" 
          DestinationFiles="$(BuildToolsArtifactOutputPath)\%(**Filename**)%(Extension)" />

To 

  <Copy SourceFiles="$(__Generated_APK)" 
          DestinationFiles="$(BuildToolsArtifactOutputPath)\%(**itemname.Filename**)%(Extension)" />

**Comment by tjxNathanMyers** [comment]
didn't mean to close

**Comment by RomaRudyak** [comment]
Hi,

In addition to this issue of debugging on iOS Device:

If iPA generation turned of this line fails:
```xml
<__Generated_dSYM Include="$([System.IO.Path]::GetDirectoryName('$(IpaPackagePath)'))\**" />
```
@dansiegel  Thanks for your work.

**Comment by dansiegel** [comment]
I'll have an updated CI Build out soon, unfortunately it'll be a bit longer until I can get something to NuGet.
