### ISSUE TITLE
Tokenized Manifest for .NET 7.0 MAUI does not have its tokens replaced

### ISSUE THREAD

**Issue by Px7-941** [dansiegel/Mobile.BuildTools#330]
# Description

The tokenized values in the Info.plist or AndroidManifest.xml are not be replaced.

## Reproduction Steps

1. Tokenize any value in the Info.plist or AndroidManifest.xml with a "$tokenname$".
2. Create a "Manifest_tokenname" entry with its value in appsettings.json.
3. Configure the buildtools.json as shown here https://mobilebuildtools.com/manifests/
4. Select Debug and [Android or iOS]-Device on Visual Studio for Mac.
5. Run the project.
6. Confirm that the tokenized values in the Info.plist or AndroidManifest.xml  were not replaced.

## Expected Behavior

The tokens should be replaced with their values. For Info.plist or AndroidManifest.xml.

## Actual Behavior

The tokens inside Info.plist or AndroidManifest.xml  were ignored.

## Environment

- OS: [macOS Ventura 13.2.1]
- IDE: [VSMac|CLI]
- BuildTools Version: [2.0.245 ]
- IDE Version: [17.5 (build 1802)]
- Build Target Framework: [net7.0-android;net7.0-ios]

**Comment by eth-ellis** [comment]
@Px7-941 Were you able to find a solution to this issue?

I am also experiencing this issue on my .NET 8 MAUI project.

**Comment by dansiegel** [comment]
duplicate #308
