### ISSUE TITLE
 The item metadata %(Filename) is being referenced without an item name

### ISSUE THREAD

**Issue by allanes87** [dansiegel/Mobile.BuildTools#34]
Hi, first of all thanks for this tool.

I have this error in "AppCenter.DemoApp", do you know how can i fix it?
```
..\.nuget\packages\mobile.buildtools\1.2.1.558\build\Mobile.BuildTools.targets(133,5): 
error MSB4095: The item metadata %(Filename) is being referenced without an item name.  Specify the item name by using %(itemname.Filename).
```

thks

**Comment by dansiegel** [comment]
this is actually a known issue reported in #33. I'm not sure what Xamarin changed that broke this, but I should have a fix out by tomorrow.
