### ISSUE TITLE
Not working when on Windows PC Visual studio

### ISSUE THREAD

**Issue by chrisgate** [dansiegel/Mobile.BuildTools#38]
I added the Mobile BuildTool and my app refused to build with below errors:

Error The expression "[System.IO.Path]::GetDirectoryName('')" iOS
                                             and
AppCenter error on android

Build i want to use it for is SCSS.

by the way when i uninstall it the solution build with no error.

Thanks

**Comment by dansiegel** [comment]
@chrisgate can you please provide a sample app that demonstrates the issue. Thanks

**Comment by dansiegel** [comment]
closing as I cannot reproduce this issue.
