### ISSUE TITLE
Error System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by chrisgate** [dansiegel/Mobile.BuildTools#4]
Severity	Code	Description	Project	File	Line	Suppression State
Error		System.IO.FileNotFoundException: Could not load file or assembly 'System.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Mobile.BuildTools.Generators.SecretsClassGenerator.Execute()
   at Mobile.BuildTools.Tools.SecretsJsonTask.Execute()

=== Pre-bind state information ===
LOG: DisplayName = System.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/
LOG: Initial PrivatePath = NULL
Calling assembly : Mobile.BuildTools, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: The same bind was seen before, and was failed with hr = 0x80070002.
	Dinkkiia.CloudUtilities	C:\Users\Chrisgate\.nuget\packages\mobile.buildtools\1.0.2\build\Mobile.BuildTools.targets	52

**Comment by dansiegel** [comment]
Thanks for reporting this... I should have an update out in a few hours

**Comment by chrisgate** [comment]
Thanks.......you are the best!!!

**Comment by dansiegel** [comment]
This issue should be resolved in 1.0.5
