### ISSUE TITLE
App Manifests - Base on .json-File when building locally

### ISSUE THREAD

**Issue by Phlash1989** [dansiegel/Mobile.BuildTools#40]
# Description #
Tokenized Manifests are great on a CI environment, but switching values while having to build locally is not as smooth. It would be great if we could have a similar approach as with App Secrets.
## Proposal ##
Look for a manifest.json in the platform projects and and replace the placeholder values in the templated manifests with the values from the file. This would play out very well with #20.

**Comment by dansiegel** [comment]
@Phlash1989 that is a fantastic idea. I’ll have to give that some thought.

**Comment by Phlash1989** [comment]
I would really appreciate to contribute, so I will also try to make some thoughts (and code) about this. In my opinion a **ManifestJsonTask** (just dropping names here) can operate on the manifest file that is already existing inside the build folder. So one can use placeholders in the default manifest files while still using the full editor support in Visual Studio.

**Comment by dansiegel** [comment]
The actual reading the Json file and updating the Manifest is pretty simple. The complexity comes from the fact that we want to update it for the build, without changing the file in-place.

**Comment by Phlash1989** [comment]
Would it be possible to copy the manifest/info.plist before build into a temp destination, then do the placeholder processing on the original file? After the build is finished, we could take the backup and place it in the original destination overwriting the processed file.
This might be a bit of a hack, but it has some advantages, like it should work independent from future changes to the build process.

**Comment by dansiegel** [comment]
If the build fails between the first task and the last then you could end up in a situation where the swap wasn't fixed. It's not really a good way to go. I'm working with the Xamarin teams to figure out what the best course of action is. I think the ultimate goal of not having to duplicate Environment Variables and even being able to keep the tokenized Manifest in-place in the project is a fantastic goal. Something I absolutely want to see.
