### ISSUE TITLE
Skipping target "TemplateManifest" because it has no outputs/inputs.

### ISSUE THREAD

**Issue by RomaRudyak** [dansiegel/Mobile.BuildTools#41]
Created project in Visual Studio for Mac.
Followed all setup steps in readme for TemplateManifest feature.

Expected result:
Target must use default settings from readme description.

Actual result:
Target worked after manually adding default properties to .csproj

**Comment by RomaRudyak** [comment]
@dansiegel I investigating this issue.
Found out that `_SdkShortFrameworkIdentifier` is empty and it breaks conditioning of detections type of project.
if I add to my project manually `<IsiOSProject>true</IsiOSProject>` all works out of the box.

**Comment by Phlash1989** [comment]
@RomaRudyak have you selected either Android or iOS as the startup project? I was running in an error myself because the shared project was still selected as the startup project, maybe this happens to you also.

**Comment by RomaRudyak** [comment]
@Phlash1989 Yes, as I tried deploy project to iPhone.

Then I build it form command line. The same result.
As I mentioned in previous comment, problem that `TargetFrameworkIdentifier` not populated and all configuration from [Mobile.BuildTools.props](https://github.com/dansiegel/Mobile.BuildTools/blob/master/Mobile.BuildTools/build/Mobile.BuildTools.props#L36) not applied.

**Comment by dansiegel** [comment]
Closing that v2.0 has rewritten how Template Manifests are handled
