### ISSUE TITLE
No Secrets.cs file is generated

### ISSUE THREAD

**Issue by adam7** [dansiegel/Mobile.BuildTools#49]
Hi there,

I've read the [blog ](https://dansiegel.net/post/2018/03/11/secure-app-builds-with-appcenter) and the wiki to try and understand how I use this package but I think I must be missing something.
I've added the NuGet package to my project, Xamarin Forms .Net Standard, dropped a file called secrets.json in the root of the project and run a build.
Now I'm expecting a Secrets.cs file to be generated but nothing. Am I missing an obvious step here or is something not working?

Thanks
Adam

**Comment by dansiegel** [comment]
@adam7 look in the `obj` folder. To help prevent accidentally checking in the Secrets class it is auto-generated in the Temporary Output Folder. Even though you won't see it in the IDE, you should be able to find it in the file system, and it should still be accessible in intellisense in the IDE.
