### ISSUE TITLE
Specific secrets.json file for a configuration

### ISSUE THREAD

**Issue by XabluBatkuip** [dansiegel/Mobile.BuildTools#51]
### SUMMARY

Have different secrets.json files for different configurations. Now we have to manually change the secrets.json properties if we change the configuration. Perhaps there is an easier way to set a specific secrets.json file for a specific configuration.

### DETAILS

Would like to specify different secrets.json file for different environments (e.g. development, staging, production, etc). Solutions could be:

- use prefixes for the secrets.json files and specify in the csproj file which json file to use for a configuration.
- Specify an array of different secrets configs in one secrets.json file, and select on the array key.
- v2.0 will have a configuration.json (https://github.com/dansiegel/Mobile.BuildTools/issues/22). Maybe can add a secrets property there.

### PLATFORMS

- [x] Android
- [x] iOS
- [x] UWP

**Comment by dansiegel** [comment]
the secrets.json file is meant for local development and should NEVER be checked into source control. To handle these scenarios you should change the variables in your build definition.

**Comment by XabluBatkuip** [comment]
Thanks Dan, I did not meant to commit in the secrets.json file into the source control. But to have an easier way to switch between environments on local builds/configurations. Now we have to edit the secrets.json file (e.g. api endpoint and token) if we want to test another environment locally.

**Comment by dansiegel** [comment]
after thinking some more on this we could support some changes for local development where we combine json files based on the build configuration. This might result in something like `secrets.debug.json` or `secrets.release.json`, if you need more than that the onus would be on you to add a build configuration that suits your needs.

**Comment by dansiegel** [comment]
this should now be completed in the v2.0 effort... you'll also have the option of doing something similar with the ConfigurationManager and app.config.
