### ISSUE TITLE
Building with dotnet cli throws "Could not load file or assembly" error

### ISSUE THREAD

**Issue by shwanton** [dansiegel/Mobile.BuildTools#53]
# Description

Trying to build via cli `dotnet build` throws error.

```
***/.nuget/packages/mobile.buildtools/1.4.0.638/build/Mobile.BuildTools.targets(56,5): error : Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
```

## Reproduction Steps

Clone [example repo](https://github.com/shwanton/DotNetBuildErrorExample)
`cd DotNetBuildErrorExample && dotnet build`

## Expected Behavior

I'm building on Appcenter in order to run UnitTests and `dotnet test` is failing during the build process.

## Actual Behavior

The build process `dotnet build` is throwing this error. 
I believe it's due to the version mismatch (Newtonsoft.json version [10.0.3](https://github.com/dotnet/cli/blob/master/src/dotnet/dotnet.csproj#L62) with the NetCore BuildTools)

## Environment

`dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

## Reproduction App

https://github.com/shwanton/DotNetBuildErrorExample

**Comment by dansiegel** [comment]
There are a lot of limitations with the dotnet cli... use `msbuild` instead
