### ISSUE TITLE
Question: debug this project while using on a project

### ISSUE THREAD

**Issue by productinfo** [dansiegel/Mobile.BuildTools#54]
Is there a way to debug this project while using on a project?

I see we can set "MobileBuildToolsDebug" to "true" on projectfile  and verify log, apart from this any other solution exists, if so could you please suggest?

**Comment by dansiegel** [comment]
Sorry for my delayed response on this...

Debugging MSBuild tasks in general is a very hard thing to do. Setting MobileBuildToolsDebug will spit out a lot of extra information. Really (and this goes well beyond simply this library) if you're having build issues I would suggest building from the command line and passing the extra argument /bl to generate a binlog which you can then open up and analyze in much more detail including seeing what variables went in/out of a Target in the build pipeline.
