### ISSUE TITLE
app.config Encryption

### ISSUE THREAD

**Issue by dansiegel** [dansiegel/Mobile.BuildTools#56]
### SUMMARY

To support best practices with the new `app.config` support in v2.0, the Mobile.BuildTools should make it extremely easy to encrypt and decrypt any `app.config` in your projects. By encrypting the config this make it safer to use in the event that the config is either checked into source control or an app package (i.e. IPA/APK) is exploded as an unencrypted config would potential expose any secrets.

**Comment by mamadou94Diop** [comment]
What about this issue ? Is this still on progress or aborted ?

**Comment by dansiegel** [comment]
it's a moot point until I stabilize a 2.0 release

**Comment by mamadou94Diop** [comment]
Thanks for the response.
Looking forward to seeing this 2.0 release be stable.

**Comment by dansiegel** [comment]
after thinking more on this, it probably would be a huge nightmare as any keys used to encrypt the app.config would need to be present in the deployed app, or we would need to decrypt the app.config at build.
