### ISSUE TITLE
Secrets file not getting made

### ISSUE THREAD

**Issue by eman1986** [dansiegel/Mobile.BuildTools#58]
I added the json file in the root and built my project but I have no intellisense for the secrets object, is this only for XF or can it be used for xamarin native and I'm just missing a critical step?

**Comment by dansiegel** [comment]
@eman1986 Mobile.BuildTools may honestly be a little misleading in name as it's actually just a bunch of MSBuild extensions that do stuff to help you. Which of course is a fancy way of saying that you can use it for any .NET project not just XF or Xamarin Native. The Secrets class should be generated in the `{rootnamespace}.Helpers` namespace. You should find the actual file generated when you build under the obj folder for example `{project root}/obj/Debug/netstandard2.0/Secrets.cs`
