### ISSUE TITLE
CI pipeline does not generate secrets.json

### ISSUE THREAD

**Issue by uioporqwerty** [dansiegel/Mobile.BuildTools#86]
I am using version 2.0.0.8480-ci of Mobile.BuildTools in my Shared Xamarin project. I have defined a buildtools.json as shown below next to my solution file:

```
{
  "$schema": "https://mobilebuildtools.com/schemas/v2/buildtools.schema.json",
  "projectSecrets": {
    "TI.Shared": {
      "delimiter": ";",
      "disable": false,
      "className": "Secrets",
      "namespace": "Helpers",
      "properties": [
        {
          "name": "AppCenter_Android_Development_Secret",
          "type": "Guid"
        },
        {
          "name": "AppCenter_iOS_Development_Secret",
          "type": "Guid"
        },
        {
          "name": "AppCenter_Android_Production_Secret",
          "type": "Guid"
        },
        {
          "name": "AppCenter_iOS_Production_Secret",
          "type": "Guid"
        }
      ]
    }
  }
}
```

In my CI pipeline for Azure DevOps I have defined the variables as "Secret_AppCenter_iOS_Production_Secret" etc..  but this is the error I get in my pipeline:

```
Build started 1/7/2020 10:39:56 PM.
Project "/Users/uioporqwerty/agents/agent_2/_work/2/s/src/TI.Android/TI.Android.csproj" on node 1 (PackageForAndroid;SignAndroidPackage target(s)).
_CleanIntermediateIfNuGetsChange:
  Creating directory "obj/Debug/stamp/".
  Creating "obj/Debug/stamp/_CleanIntermediateIfNuGetsChange.stamp" because "AlwaysCreate" was specified.
_ResolveSdks:
  Found Java SDK version 1.8.0.
  Found Java SDK version 1.8.0.
_ValidateAndroidPackageProperties:
    PackageName: org.ti.mobile
Project "/Users/uioporqwerty/agents/agent_2/_work/2/s/src/TI.Android/TI.Android.csproj" (1) is building "/Users/uioporqwerty/agents/agent_2/_work/2/s/src/TI.Shared/TI.Shared.csproj" (2:2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "obj/Debug/netstandard2.0/".
ProcessScss:
Skipping target "ProcessScss" because it has no outputs.
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
BuildHostSecrets:
  Output Path: /Users/uioporqwerty/agents/agent_2/_work/2/s/src/TI.Shared/secrets.json
      No Build Host Secrets Found...
Secrets:
  No Secrets Json File was found.
```

And then it eventually fails because it cannot find the namespace Helpers in TI.Shared. Is there a step I'm missing to set this up? I've combed through the docs and can't find a reason why it should be failing to generate.

**Comment by uioporqwerty** [comment]
<img width="495" alt="image" src="https://user-images.githubusercontent.com/4053751/71997463-ccde5600-3235-11ea-9659-976a0c7117fc.png">

**Comment by dansiegel** [comment]
There are several known issues currently with the 2.0 CI builds which is why I haven't released a preview

**Comment by omatrot** [comment]
@dansiegel Is there anything I can do to help?
I need this to work for one of my Xamarin Android App.
Thanks in advance.

**Comment by dansiegel** [comment]
@omatrot right now I'm going through the E2E projects as I have time. That said for the v2 CI builds, they should be generating the secrets.json from what I can tell.. but I may have a test not doing something properly... I'll have to double check.

**Comment by dansiegel** [comment]
I've updated the integration tests to validate that they are generating the secrets.json in a CI pipeline and that is all working. You can look at the E2E folder to see how I've done that.
