### ISSUE TITLE
Template Manifest task is skipped

### ISSUE THREAD

**Issue by omatrot** [dansiegel/Mobile.BuildTools#87]
# Description

I'm Using the official NuGet 1.4.0.638 in a Xamarin.Android project.

My CI pipeline is running on AppCenter.

The behaviour is that no Manifest is generated and the build fails.

I have the following output in the logs:

TemplateManifest:
Skipping target "TemplateManifest" because it has no outputs.
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(730,2): error : AndroidManifest file does not exist [/Users/runner/runners/2.163.1/work/1/s/etp_proto/etp_proto/etp_proto.csproj]
Done Building Project "/Users/runner/runners/2.163.1/work/1/s/etp_proto/etp_proto/etp_proto.csproj" (PackageForAndroid;SignAndroidPackage target(s)) -- FAILED.

Build FAILED.
It doesn't work locally either (VS for Mac 8.4)

## Reproduction Steps

I'm probably missing something here but without a proper error message including a full template path I can't provide reproduction steps.

## Expected Behavior

A manifest generated in the app Properties directory.

## Actual Behavior

No AndroidManifest.xml is generated.

I have defined the following environment variables in AppCenter:

Manifest_PackageName => **com.mycompany.myapp**
BuildResourcesDirRootPath => **etp_proto/etp_proto/mobile.buildtools-templates** 

The directory structure is:
etp_proto/ => solution directory
etp_proto/ => project directory
mobile.buildtools-templates/ => Resource folder that contains the AndroidTemplateManifest.xml file.
The template directory is not located under the solution directory.

## Environment

- OS: [OSX]
- IDE: [VSMac]
- BuildTools Version: [1.4.0.638]
- IDE Version: [8.4]
- Build Target Framework: [Xamarin.Android]

## Reproduction App

N/A

**Comment by dansiegel** [comment]
closed via #88
