### ISSUE TITLE
Android : Sync Doc and code

### ISSUE THREAD

**Issue by omatrot** [dansiegel/Mobile.BuildTools#89]
# Description

Either the documentation or the task configuration is wrong:

```xml
    <TemplateManifestTask ConfigurationPath="$(BuildToolsConfigFilePath)"
                          ProjectName="$(MSBuildProjectName)"
                          ProjectDirectory="$(MSBuildProjectDirectory)"
                          SolutionDirectory="$(SolutionDir)"
                          IntermediateOutputPath="$(IntermediateOutputPath)"
                          TargetFrameworkIdentifier="$(TargetFrameworkIdentifier)"
                          ReferenceAssemblyPaths="$(_XATargetFrameworkDirectories)"
                          ManifestPath="$(TemplateAppManifest)"
                          Condition="$(BuildToolsEnableTemplateManifests)" />
```

The Task is passed an environment variable named `TemplateAppManifest` while the [wiki](https://github.com/dansiegel/Mobile.BuildTools/wiki/Tokenized-Android-&-iOS-Configurations) says it is called `TemplateManifestPath`

## Reproduction Steps

N/A

## Expected Behavior

The Wiki in sync with the code.

## Actual Behavior

N/A

## Environment

- OS: [OSX]
- IDE: [VSMac]
- BuildTools Version: [2.0.873-ci]
- Build Target Framework: [Xamarin.Android]

## Reproduction App
N/A

**Comment by dansiegel** [comment]
This is not actually a sync problem as much as the feature you're referencing works completely different between 1.x & 2.x. The wiki docs are accurate for 1.x., where as 2.x actually is meant to do in-place templating.
