### ISSUE TITLE
Customise secrets.json location

### ISSUE THREAD

**Issue by Lelelo1** [dansiegel/Mobile.BuildTools#92]
### SUMMARY

Enable the `secrets.json` to be set to a custom location somewhere on the computer. 

### DETAILS

With the current situation - the `secrets.json` seems to have to be placed inside the root of the project: https://stackoverflow.com/questions/51621387/how-can-i-use-set-environment-variables-in-xamarin-forms-from-app-center
With that setup one can either forget to add the file to `.gitignore` and push, or when recloning a project - accidentally forgetting to save the file. 

My own use case would have been satisfied by setting a system environment variable. However it does not seem possible on a mac and with dotnet.
By being able place the `secrets.json` outside the project somewhere on my disk it would persists deletion and recloning of the project - while still being safe.

### HOW

Probably the procedure of reading the json could be refined by determining wether it contains a url (leading to secrets), or is the actual secrets file that should be used.
I have not yet looked through the source code. 

### PLATFORMS

- [true ] Android
- [true ] iOS
- [true ] UWP
**(Xamarin Forms)**

**Comment by dansiegel** [comment]
2.0 ensures that secrets.json is in the .gitignore and adds it if it's missing
