### ISSUE TITLE
[Feature] Add support for SVG images

### ISSUE THREAD

**Issue by dansiegel** [dansiegel/Mobile.BuildTools#94]
### SUMMARY

More and more people love to use SVG's... The Mobile.BuildTools Image support should also support SVGs.

### DETAILS

When the Mobile.BuildTools encounters an SVG rather than throwing an exception as we currently do, we should pre-render the various resource sizes. This will require some additional support as we may not have a specific size for the full size image. This may require some changes to the supported attributes of the resource definition json file.

### PLATFORMS

- [x] Android
- [x] iOS
- [x] UWP

**Comment by beeradmoore** [comment]
I was just thinking about SVG on Android and wondering if people use it over png. 
If people use SVG it would be good if this tool could use svg for Android, generate png in folders for Android < API 21 (if the minimum version is less than this of course), generate png for iOS, etc.

**Comment by dansiegel** [comment]
generally SVG images are way better to generate the pngs from since they scale a lot better... but I haven't had a chance to look into this more.

**Comment by bijington** [comment]
As per our chat I am currently exploring making use of SkiaSharp instead of ImageSharp to solve the SVG support

**Comment by bijington** [comment]
Changes appear to be coming along nicely. I have SVG support in through the use of SkiaSharp, I need to work through reintroducing Watermark and Padding support.
